<?php
include('core/php/incl.php');
if($logged_in) {
	header("Location: dashboard.php");
	exit();
}
?>
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Quicure | Quick &amp; Secure</title>
		<link href="core/css/style.css" rel="stylesheet" type="text/css">
		<link href="core/css/font-awesome.css" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,800,700,800' rel='stylesheet' type='text/css'>
		<meta name="robots" content="noindex, nofollow">
		<!-- html5.js for IE less than 9 -->
		<!--[if lt IE 9]>
			<script src="core/js/html5.js"></script>
			<script src="core/js/front/css3-mediaqueries.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="https://quicure.com/core/img/favicon.png">
		<?php require_once('core/php/chat.php'); ?>
	</head>
	<body>
		<?php include('core/php/header.php'); ?>
		<div class="front_header">
			<div class="container clearfix">
		    	<div class="front_header_left">
		        	<h1>Invoicing, just better.</h1>
		            <p>Easily create and send professional-looking invoices from a convenient online control panel. Pay your employees and manage your expenses all in one dashboard.</p>
		            <div class="register_button">
		            	<a href="#register">Register for Free</a>
		                No Monthly fees or charges
		            </div>
		        </div>
		        
		        <div class="front_header_right">
		        	<div class="inovice"><img src="core/images/invoice.png"></div>
		            <div class="Easy_Requisitions">
		            	<h2>Simplicity</h2>
		                <p>Duplicate your invoice and re-use products / services with one click. Once you've set up your Quicure account, sending an invoice takes less than 30 seconds.</p>
		            </div>
		        </div>
		    </div>
		    
		    <div class="cloud"></div>
		</div>
		<div class="featured_section">
	    	<div class="container">
	        	<h1>No Monthly Fees or Charges</h1>
	            <h1 style="font-size: 8em">$0.30 + 2.9%</h1>
	        </div>
	    </div>
		<div class="client_views">
	    	<div class="container">
	        	<div class="pc_bg">
	            	<div class="client_views_content">
	                	<h1>Look like a Pro</h1>
	                    <p>Invoices generated by Quicure are fully branded (for free). You can email them or even print them out and send them by post. The Quicure logo will never appear on your invoices or emails.<br><br><br><br></p>
	                    
	                </div>
	                <div class="register_button">
	            			<a href="#register">Register for Free</a>
	                		No Monthly fees or charges
	            		</div>
	            </div>
	        </div>
	        <div class="book_bg"></div>
	    </div>
		<div class="easy_paid">
	    	<div class="container">
	        	<h1>Make Getting Paid As Easy As Pie</h1>
	            <div class="Getting_Paid clearfix">
	            	<div class="Getting_Paid_img"><img src="core/images/paid.jpg"></div>
	                <div class="getting_content">
	                Your clients can pay you with their PayPal balance, using their credit card, or instant-transfer from their bank account. Quicure takes a small transaction fee (less than 5%) and the rest of the money goes directly to your bank account or PayPal wallet.
	                </div>
	            </div>
	            
	            <div class="register_button">
	            	<a href="#register">Register for Free</a>
	               	No Monthly fees or charges
	            </div>
	        </div>
	    </div>
		<div class="how_it_works">
	    	<div class="container">
	        	<h1>How It Works</h1>
	            <ul class="clearfix">
	            	<li>
	                	<span class="process_icon"><i class="fa fa-file-text"></i></span>
	                	<h3>Send Invoices</h3>
	                    <p>Create invoices using the convinent online dashboard. Re-use existing products &amp; services with one click.</p>
	                </li>
	                <li>
	                	<span class="process_icon"><i class="fa fa-money"></i></span>
	                	<h3>Accept Payments</h3>
	                    <p>Your clients can pay online with PayPal. You get cash directly in your PayPal or bank account.</p>
	                </li>
	                <li>
	                	<span class="process_icon"><i class="fa fa-refresh"></i></span>
	                	<h3>Pay your Employees</h3>
	                    <p>Set up payroll and forget about it. Quicure will automatically pay your employees so you don't have to.</p>
	                </li>
	            </ul>
	        </div>
	    </div>
	<div class="company_billling">
		<div class="container">
			<h2>Join a growing community using Quicure to make billing painless.</h2>
			<img src="core/images/billing.jpg">
	    </div>
	    <div class="trangle"></div>
	</div>
	<div class="newletter">
		<div class="container clearfix" id="register">
	    	<form action="register" method="post">
	        	<input type="text" class="textbox" placeholder="Company Name" name="first_name"> <input type="text" class="textbox" placeholder="Email Address" name="email">  
	            <div class="register_button">
	            	<input style="padding: 8px 24px;" type="submit" value="Register for Free" />
	                No Monthly fees or charges
	            </div>
	        </form>
	    </div>
	</div>
	<?php
	require_once('core/php/footer.php');
	?>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script>
	$(".register_button a").click(function(){
		$('body').animate({
		    scrollTop: $("#register").offset().top
		}, 2000);
	});
	</script>
	</body>
</html>